[package]
name = "kingrust"
version = "0.1.0"
authors = ["kingbri <bdashore3@gmail.com>"]
edition = "2018"

[dependencies]
tokio  = { version = "0.2", features = ["macros"] }
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
pretty_env_logger = "0.4.0"
rand = "0.7.3"

[dependencies.serenity]
git = "https://github.com/Lakelezz/serenity/"
branch = "await"